platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/terraform
    tag: terraform-0.13.3
    username: ((docker_hub_username))
    password: ((docker_hub_authtoken))
inputs:
  - name: govuk-infrastructure-commit
  - name: frontend
  - name: content-store
  - name: publisher
  - name: publishing-api
  - name: router
  - name: router-api
  - name: signon
  - name: static
params:
  APPLICATION:
  DEPLOYMENT:
  ASSUME_ROLE_ARN: 'arn:aws:iam::430354129336:role/govuk-concourse-deployer'
  AWS_REGION: eu-west-1
  TF_IN_AUTOMATION: true
run:
  path: sh
  args:
  - '-c'
  - |
    set -eux
    IMAGE_TAG=$(cat "$APPLICATION/.git/ref")
    cd "govuk-infrastructure-commit/repo/terraform/deployments/apps/$DEPLOYMENT"
    terraform init -backend-config "role_arn=$ASSUME_ROLE_ARN"
    terraform plan \
      -var "assume_role_arn=$ASSUME_ROLE_ARN" \
      -var-file ../../variables/test/common.tfvars \
      -var-file ../../variables/test/apps.tfvars \
      -var "image_tag=deployed-to-production"
